apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.96
    path: /nfs-share/kubernetes/gua
  persistentVolumeReclaimPolicy: Retain
