apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: web-app
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          value: mysql
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: web-app
spec:
  ports:
  - port: 80
  selector:
    app: phpmyadmin
