apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs-pv
spec:
  storageClassName: nginx-nfs-sc
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/kubernetes/k8s-nginx-nfs
    server: 192.168.0.96
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-nfs-pvc
spec:
  storageClassName: nginx-nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-nfs-volume
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-nfs-volume
        persistentVolumeClaim:
          claimName: nginx-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 80
  type: LoadBalancer
