apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginx
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: PMA_HOST
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: MYSQL_DATABASE
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: MYSQL_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 80